### ISSUE TITLE
extension activeEvent should not  use * and replaced by commands

### ISSUE THREAD

**Issue by tjx666** [ultram4rine/vscode-choosealicense#82]

**Comment by ultram4rine** [comment]
Maybe a better solution would use onStartupFinished. As says in docs it's similar to * but not slow down vscode startup.

**Comment by tjx666** [comment]
@ultram4rine why not set activeOnCommand:

**Comment by ultram4rine** [comment]
Hi @tjx666, I don't want to set `activationEvents` `onCommand` because, firstly, I don't want to wait for activation when use command, and, secondly, I can forget to add new command to the list of activation events.

**Comment by tjx666** [comment]
I use this extension very rarely. I may disable it util I need it next time.

**Comment by ultram4rine** [comment]
I took a look at the other similar extensions, so I will change it to `onCommand`.
