### ISSUE TITLE
lgpl-3.0 missing

### ISSUE THREAD

**Issue by lapaDevAdmin** [ultram4rine/vscode-choosealicense#831]
Can you add or update license list ? i cant found lgpl-3.0
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

https://docs.github.com/en/rest/licenses/licenses?apiVersion=2022-11-28#get-all-commonly-used-licenses

**Comment by ultram4rine** [comment]
Hi @lapaDevAdmin , is that a correct license? https://api.github.com/licenses/lgpl-3.0

**Comment by lapaDevAdmin** [comment]
> Hi @lapaDevAdmin , is that a correct license? https://api.github.com/licenses/lgpl-3.0

yes it is :)
